name: Build and Push to ECR (latest)

on:
  push:
    branches:
      - main
      - test

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create ECR repository if not exists
        run: |
          aws ecr describe-repositories --repository-names indicadores-frontend || \
          aws ecr create-repository --repository-name indicadores-frontend

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Fetch secrets from AWS Secrets Manager
        id: secrets
        run: |
          SECRET_ARN="arn:aws:secretsmanager:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:secret:indicadores-frontend/env-DfgMDk"

          SECRET_JSON=$(aws secretsmanager get-secret-value \
            --secret-id "$SECRET_ARN" \
            --query SecretString --output text)

          REACT_APP_LOCAL_URL=$(echo "$SECRET_JSON" | jq -r '.REACT_APP_LOCAL_URL')
          REACT_APP_PROD_URL=$(echo "$SECRET_JSON" | jq -r '.REACT_APP_PROD_URL')

          echo "REACT_APP_LOCAL_URL=$REACT_APP_LOCAL_URL" >> $GITHUB_ENV
          echo "REACT_APP_PROD_URL=$REACT_APP_PROD_URL" >> $GITHUB_ENV


      - name: Build and push Docker image to ECR
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/indicadores-frontend:latest
          build-args: |
            REACT_APP_LOCAL_URL=${{ env.REACT_APP_LOCAL_URL }}
            REACT_APP_PROD_URL=${{ env.REACT_APP_PROD_URL }}
